version: '3'
services:
  reverseproxy:
    build: ./reverse-proxy/
    image: reverseproxy
    container_name: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/cache:/data/nginx/cache
    # restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - reverseproxy
    # restart: always

  apache:
    image: httpd:alpine
    depends_on:
      - reverseproxy
    # restart: always